### ISSUE TITLE
NERSC Perlmutter package.yaml

### ISSUE THREAD

**Issue by kwryankrattiger** [spack/spack-configs#39]
It seems that the current `site_config/package.yaml` is a little out of date already.

cray-mpich 8.1.10 -> 8.1.11
no cuda/11.3.0 module, use cudatoolkit/21.9_11.4
nvidia 21.7 -> 21.9
libfabric 1.11.0.4.79 -> 1.11.0.4.75

**Comment by shahzebsiddiqui** [comment]
@kwryankrattiger thanks for bringing this up, I am aware of this bcz our system got upgraded to CPE 21.11 and this was based on 21.10. I have the changes you mentioned and this will be addressed once I get E4S rebuilt
