### ISSUE TITLE
packages.yaml non properly configured wheh installing on graviton2

### ISSUE THREAD

**Issue by usumfabricae** [spack/spack-configs#59]
The installation script [postinstall.sh](https://github.com/spack/spack-configs/blob/main/AWS/parallelcluster/postinstall.sh) when started on graviton2 instance is trying to download packages-neovers_n1.yaml  that does not exists.
Please rename [packages-graviton2.yaml](https://github.com/spack/spack-configs/blob/main/AWS/parallelcluster/packages-graviton2.yaml) into packages-neovers_n1.yaml

**Comment by stephenmsachs** [comment]
Yes, you are right. On it.

**Comment by stephenmsachs** [comment]
Done.
