### ISSUE TITLE
AWS postinstall.sh script doesn't work for Ubuntu 20 based parallel clusters

### ISSUE THREAD

**Issue by steevmi1** [spack/spack-configs#69]
I tried to launch an ubuntu-based parallelcluster, and the postinstall.sh script fails due to python2/python3 confusion. The pip command comes from the python3-pip package (verified with dpkg -S /usr/bin/pip), but /usr/bin/env python finds python 2.7.18, which doesn't have the pyyaml package installed.

**Comment by stephenmsachs** [comment]
Thanks for reporting. Should be fixed now.
