### ISSUE TITLE
Error while installing with parallel cluster and graviton 3 (c7g instances)

### ISSUE THREAD

**Issue by usumfabricae** [spack/spack-configs#73]
For c7g instances architecture is neoverse_v1.

During execution of /AWS/parallelcluster/postinstall.sh it looks for file **AWS/parallelcluster/packages-neoverse_v1.yaml** but this file is missing in the repository.
I think it should be enough copying packages-neoverse_n1.yaml to packages-neoverse_v1.yaml to solve this issue.

**Comment by stephenmsachs** [comment]
At the moment it will fall back to `packages-aarch64.yaml`. I am still working out some kinks to use arm compiler for a lot of things on c7g as it provides better perfomance. Feel free to use `packages-neoverse_v1.yaml` in the meantime.

**Comment by stephenmsachs** [comment]
Fixed in https://github.com/spack/spack-configs/commit/7dbd62a775c3fe8a1ef2da1726dc1fe8d5e7fc48
