### ISSUE TITLE
Issue with gromacs definitions in the packages.yaml files

### ISSUE THREAD

**Issue by steevmi1** [spack/spack-configs#78]
The gromacs entries in the packages.yaml file look to reference a couple of variants that no longer exist in the actual package spec, +blas and +lapack. This leads to errors when trying to concretize:

```
[buildhpc@hpcbuild01]$ spack spec gromacs
==> Error: cannot emit requirements for the solver: variant "blas" not found in package "gromacs" [required from package "gromacs"]
```

**Comment by stephenmsachs** [comment]
Thanks for reporting. Am I correct to assume that you are looking at the `packages-*.yaml` files under `AWS/parallelcluster`?

**Comment by steevmi1** [comment]
Yes, sorry for not specifying that.

**Comment by stephenmsachs** [comment]
OK, that's fixed now.
