### ISSUE TITLE
acfl  is compiling from source at every set-up

### ISSUE THREAD

**Issue by usumfabricae** [spack/spack-configs#79]
Could you please add an option to /AWS/parallelcluster/postinstall.sh, to avoid installing acfl arm compiler like the one already existing for intel compiler ( --no-intel-compiler)

It is taking a lot of time to set-up since it is not included in binary cache

**Comment by stephenmsachs** [comment]
Thanks for the suggestion. Added option in https://github.com/spack/spack-configs/commit/25a767103dde3865c71c9b2ae9542417392126e4
